version: "3"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
   mynet:
     driver: bridge
     ipam:
      config:
        -  subnet: 10.10.1.0/24

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
        mynet:
          ipv4_address: 10.10.1.10
    restart: always

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '9093:9093'
    volumes:
      - "kafka_data:/bitnami"
#      - "/home/lion/Documents/kafka/:/home"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://192.168.10.161:9092,EXTERNAL://192.168.10.161:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    networks:
        mynet:
          ipv4_address: 10.10.1.11
    restart: always

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
     - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=kafkadocker
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCO=true
    depends_on:
      - kafka
    networks:
        mynet:
          ipv4_address: 10.10.1.12
    restart: always