FROM ubuntu:20.04
RUN touch /opt/test.txt
# CMD [ "systemctl start asterisk", "/bin/bash" ]

# docker build -t testubuntu .
# docker run -it -p 5060:5060/udp -p 10000-20000:10000-20000/udp -p 5022:5022/udp -v /some/folder/:/home/ asterisk  