{
 "title": "Zookeeper Overview",
 "tags": [ "kafka-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(zookeeper_status_quorumsize, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(zookeeper_status_quorumsize{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Health Check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Zookeeper nodes online",
   "type": "stat",
   "description": "Quorum Size of Zookeeper ensemble",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zookeeper_status_quorumsize{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "stat",
   "description": "Number of Alive Connections",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_numaliveconnections{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "graph",
   "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zookeeper_outstandingrequests{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(zookeeper_inmemorydatatree_nodecount{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Number of Watchers",
   "type": "stat",
   "description": "Number of Watchers",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zookeeper_inmemorydatatree_watchcount{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Used:{{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_max{job=~\"$job\",instance=~\"$instance\",area=\"heap\"}",
     "legendFormat": "Max:{{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Latency - Minimum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zookeeper_minrequestlatency{instance=~\"$instance\",job=~\"$job\"} * zookeeper_ticktime{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Average",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zookeeper_avgrequestlatency{instance=~\"$instance\",job=~\"$job\"} * zookeeper_ticktime{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  },
  {
   "title": "Request Latency - Maximum",
   "type": "graph",
   "description": "Amount of time it takes for the server to respond to a client request",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "zookeeper_maxrequestlatency{job=~\"$job\",instance=~\"$instance\"} * zookeeper_ticktime{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{server_name}}:({{instance}})"
    }
   ]
  }
 ]
}