{
 "title": "RTPEngine",
 "description": "RTPEngine Kamailio",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Response",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response ALLIN",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "target": "response.auth.*" },
      { "target": "response.200" },
      { "target": "response.302" },
      { "target": "response.404" }
     ]
    },
    {
     "title": "Response 200",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "target": "response.200" }
     ]
    },
    {
     "title": "Response auth",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "target": "response.auth.*" }
     ]
    },
    {
     "title": "Response 404",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "target": "response.404" }
     ]
    },
    {
     "title": "Response 302",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      { "target": "response.302" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU-0",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "target": "collectd.graphite.cpu-0.*" }
     ]
    },
    {
     "title": "CPU-1",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "target": "collectd.graphite.cpu-1.*" }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "df-root",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "target": "collectd.graphite.df-root.*" }
     ]
    },
    {
     "title": "disk-dm-0",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "target": "collectd.graphite.disk-dm-0.*.*"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "SWAP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      { "target": "collectd.graphite.swap.*" }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      { "target": "collectd.graphite.memory.*" }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interface-eth0 (RX)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "target": "collectd.graphite.interface-eth0.*.rx"
      }
     ]
    },
    {
     "title": "Interface-eth0 (TX)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "target": "collectd.graphite.interface-eth0.*.tx"
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "targets": [
      { "target": "collectd.graphite.processes.*" }
     ]
    }
   ]
  },
  { "title": "Other metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "target": "brubeck.errors" },
    { "target": "brubeck.metrics" },
    { "target": "brubeck.unique_keys" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "target": "carbon.aggregator.98ac736386f4-a.*"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "target": "carbon.agents.98ac736386f4-a.*" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "target": "view.POST.*" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "target": "view.GET.*" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "view.graphite.*.*.*.*.*.*" }
   ]
  }
 ]
}