version: '3.1'

services:    
  grafana:
    image: grafana/grafana
    container_name: grafana-app
    restart: always
    ports:
      - 3000:3000
  
  prometheus:
    image: bitnami/prometheus
    container_name: prometheus-app
    restart: always
    ports:
      - 9090:9090