# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
       - /home/lion/podman/mariadb:/var/lib/mysql
       - /home/lion/podman/mariadb:/run/mysqld  
#       - /otp/rra/mysql:/var/lib/mysql
#       - /otp/rra/mysql:/run/mysqld
    command: sh -c 'exec mysql -uroot -p"$MARIADB_ROOT_PASSWORD"' < /home/lion/folder_name/DB.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1