# Use root/example as user/password credentials
version: '3.1'

services:    
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 112233445566
    volumes:
      - /home/nameuser/podman/mariadb:/var/lib/mysql
      - /home/nameuser/podman/mariadb:/run/mysqld

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1